services:
  db:
    image: postgres:17-alpine
    container_name: db
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    env_file:
      - ./.env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - niunmango_network

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile
      target: development
    container_name: backend
    restart: unless-stopped
    volumes:
      - ./server:/app
      - node_modules_server:/app/node_modules
    env_file:
      - ./.env
    ports:
      - "3001:3001"
    environment:
      NODE_ENV: ${NODE_ENV}
      PORT: 3001
      DATABASE_URL: ${DATABASE_URL}
      CLIENT_URL: ${CLIENT_URL}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - db
    networks:
      - niunmango_network
    command: npm run dev

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile
      target: development
    container_name: frontend
    restart: unless-stopped
    env_file:
      - ./.env
    volumes:
      - ./client:/app
      - node_modules_client:/app/node_modules
    environment:
      NODE_ENV: ${NODE_ENV}
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_APP_NAME: NiunManApp
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - niunmango_network
    command: npm run dev

volumes:
  postgres_data:
  node_modules_client:
  node_modules_server:

networks:
  niunmango_network:
